apiVersion: v1
kind: Secret
metadata:
  name: cluster1-secrets
type: Opaque
stringData:
  root: root_password
  xtrabackup: backup_password
  monitor: monitor_password
  #  pmmserverkey: my_pmm_server_key
  operator: operator_password
  replication: replication_password
  # note that orchestrator password cannot contain underscores
  orchestrator: orchestrator_password
  heartbeat: heartbeat_password
